### PR TITLE
Add instructions for cmd.exe wrapper to README.md

### PR DESCRIPTION
**Pull request by eggbean**
Working fine here.

### CODE REVIEW

**Comment by shilangyu** [comment]
Thanks! If you'd like, we can include this snippet somewhere behind a CLI flag if you find it appropriate. Not sure if we can mimic a similar behavior to powershell where we use the `scoop` name directly.

**Comment by eggbean** [comment]
I'm not sure what you mean by that. Do you mean the syntax hightlighting on GitHub? Windows batch is not supported if that's what you mean. https://codemirror.net/5/mode/index.html

That wrapper isn't working for me at the moment, so don't merge the README.md until I have figured out what's going on. Cheers.

**Comment by eggbean** [comment]
I realised that the actual search wasn't working, as the `shift` command wasn't doing anything, so it was always searching for "search". It works now and I have added it to my scripts.

**Comment by shilangyu** [comment]
Thanks!

> I'm not sure what you mean by that

I meant that just like we have `scoop-search --hook` that prints the powershell function, we could have a `scoop-search --cmd-wrapper` to print the code you just included in the readme. Either way, can be done in a separate PR if needed.

**Comment by eggbean** [comment]
> I meant that just like we have `scoop-search --hook` that prints the powershell function, we could have a `scoop-search --cmd-wrapper` to print the code you just included in the readme.

Oh, I see. Yes, that would be nice for users to redirect the a file. That would be something for your binary though. I don't know Golang yet, but I do plan to learn it soon.

**Pull request merged**
