### PR TITLE
#57

### PR DESCRIPTION
**Pull request by skanda890**
#57

### CODE REVIEW

**Comment by shilangyu** [comment]
I don't understand the purpose of this change. Can you explain please?

**Comment by skanda890** [comment]
See #57

**Comment by skanda890** [comment]
Can you change everything that you did in #57.

**Comment by shilangyu** [comment]
I see #57, but I don't understand why the binary is being pushed to the repo. Is there some specific issue you are trying to solve? Maybe I can help?

**Comment by skanda890** [comment]
Think so this explains it: image

**Comment by shilangyu** [comment]
Unfortunately I do not understand and you are not telling me why this is being done. Feel free to open an issue instead, I will be happy to help.

**Pull request closed without merging**
